### ISSUE TITLE
Fails to Render in Android Studio

### ISSUE THREAD

**Issue by ShriekBob** [daimajia/NumberProgressBar#15]
When using the library as described, with the following XML:
    <com.daimajia.numberprogressbar.NumberProgressBar
        android:id="@+id/summary_card_monthly_progress"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        style="@style/NumberProgressBar_Default"
        />

Android Studio gives the following Rendering error:

Missing styles. Is the correct theme chosen for this layout?  Use the Theme combo box above the layout to choose a different layout, or fix the theme style references.  Failed to find style 'numberProgressBarStyle' in current theme (2 similar errors not shown)

**Comment by saeid-pm** [comment]
You can check this http://stackoverflow.com/questions/13439486/missing-styles-is-the-correct-theme-chosen-for-this-layout.

It seems that this warning won't affect the compiling. So, take easy, just ignore it.

**Comment by Dona278** [comment]
Try with https://github.com/Dona278/NumberProgressBar

**Comment by daimajia** [comment]
The latest version Android Studio can render this lib correctly.  The time tell us that it is not the problem of the lib. hahha.
