### ISSUE TITLE
Attributes already defined

### ISSUE THREAD

**Issue by willylatorre** [daimajia/NumberProgressBar#17]
When using NumberProgressBar library with MaterialDesign library, this error popups up

Error:(1) Attribute "progress" has already been defined
Error:(1) Attribute "max" has already been defined

It is recomended to have prefixes as explained here https://code.google.com/p/android/issues/detail?id=22576

**Comment by daimajia** [comment]
Yeah, I think prefix when defining the attributes is needed.

**Comment by d7coders** [comment]
I have the same problem
any solution?

**Comment by stormlei** [comment]
@daimajia Error:(486) Attribute "progress_text_visibility" already defined with incompatible format.

**Comment by Dona278** [comment]
Try with https://github.com/Dona278/NumberProgressBar
All of attributes are renamed to prevent conflicts with other libraries

**Comment by daimajia** [comment]
Fixed in v1.3, please check it. 

BTW. `max` has been changed to `progress_max` , `progress` -> `progress_current`

**Comment by xty19** [comment]
> Try with https://github.com/Dona278/NumberProgressBar
> All of attributes are renamed to prevent conflicts with other libraries

thanks very much
