### ISSUE TITLE
Attributes not work?

### ISSUE THREAD

**Issue by crysan** [daimajia/NumberProgressBar#18]
Hi!

```
<com.daimajia.numberprogressbar.NumberProgressBar
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"

        custom:progress_unreached_bar_height="4dp"
        custom:progress_reached_bar_height="8dp"

        custom:max="100"
        custom:progress="80"
         />
```

Unfortunately the height of the bar does not change.
Is this a bug?

**Comment by daimajia** [comment]
I made a demo, it works right. Could you please provide your layout xml?

**Comment by crysan** [comment]
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:paddingLeft="24dp"
    android:paddingRight="24dp"
    android:paddingTop="24dp">

    <com.daimajia.numberprogressbar.NumberProgressBar
        xmlns:custom="http://schemas.android.com/tools"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:id="@+id/progress1"
        custom:progress_unreached_bar_height="4dp"
        custom:progress_reached_bar_height="8dp"
        custom:progress_text_size="16dp"/>

    <TextView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:id="@+id/tTitle1"
        android:layout_below="@id/progress1"
        android:paddingTop="8dp"
        android:textSize="16dp"
        android:maxLines="1"
        android:ellipsize="end"
        android:singleLine="true"/>

    <View
        android:layout_width="match_parent"
        android:layout_height="24dp"
        android:id="@+id/v1"
        android:layout_below="@id/tTitle1"/>

    <com.daimajia.numberprogressbar.NumberProgressBar
        xmlns:custom="http://schemas.android.com/tools"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:id="@+id/progress2"
        android:layout_below="@id/v1"
        custom:progress_unreached_bar_height="4dp"
        custom:progress_reached_bar_height="8dp"
        custom:progress_text_size="16dp"/>

    <TextView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:id="@+id/tTitle2"
        android:layout_below="@id/progress2"
        android:paddingTop="8dp"
        android:paddingBottom="16dp"
        android:textSize="16dp"
        android:maxLines="1"
        android:ellipsize="end"
        android:singleLine="true"/>

</RelativeLayout>

**Comment by crysan** [comment]
Do not have time?

**Comment by crysan** [comment]
Where are you missing?

**Comment by daimajia** [comment]
Are you using eclipse jar vertion rather than gradle or maven?

**Comment by crysan** [comment]
gradle

**Comment by daimajia** [comment]
Can you paste your layout xml here?

**Comment by crysan** [comment]
<RelativeLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:custom="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:paddingLeft="24dp"
    android:paddingRight="24dp"
    android:paddingTop="24dp">

    <com.daimajia.numberprogressbar.NumberProgressBar
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:id="@+id/progress1"
        custom:style="@style/umberProgressBar_Passing_Green"
        custom:progress_unreached_bar_height="4dp"
        custom:progress_reached_bar_height="8dp"
        custom:progress_text_size="16dp"/>

    <TextView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:id="@+id/tTitle1"
        android:layout_below="@id/progress1"
        android:paddingTop="8dp"
        android:textSize="16dp"
        android:textStyle="bold"
        android:maxLines="1"
        android:ellipsize="end"
        android:singleLine="true"/>

    <View
        android:layout_width="match_parent"
        android:layout_height="24dp"
        android:id="@+id/v1"
        android:layout_below="@id/tTitle1"/>

    <com.daimajia.numberprogressbar.NumberProgressBar
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:id="@+id/progress2"
        android:layout_below="@id/v1"
        custom:style="@style/NumberProgressBar_Relax_Blue"
        custom:progress_unreached_bar_height="4dp"
        custom:progress_reached_bar_height="8dp"
        custom:progress_text_size="16dp"/>

    <TextView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:id="@+id/tTitle2"
        android:layout_below="@id/progress2"
        android:paddingTop="8dp"
        android:paddingBottom="16dp"
        android:textSize="16dp"
        android:maxLines="1"
        android:ellipsize="end"
        android:singleLine="true"/>


</RelativeLayout>

**Comment by daimajia** [comment]
Which version you are using currently?

**Comment by crysan** [comment]
compile 'com.daimajia.numberprogressbar:library:1.2@aar'

**Comment by daimajia** [comment]
```xml
    <com.daimajia.numberprogressbar.NumberProgressBar
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:id="@+id/progress1"
        custom:style="@style/umberProgressBar_Passing_Green" // here  should be style="@style/NumberProgressBar_Passing_Green"
        custom:progress_unreached_bar_height="4dp"
        custom:progress_reached_bar_height="8dp"
        custom:progress_text_size="16dp"/>
```

**Comment by crysan** [comment]
Yes, the styles have earned! And what about the custom: progress_unreached_bar_height = "4dp"? This option would not change the line thickness.

**Comment by daimajia** [comment]
![image](https://cloud.githubusercontent.com/assets/2503423/7466171/bf7afdb0-f310-11e4-92fa-8e6ee2d8330b.png)

It's weird, I use the following layout, it works alright.

```xml

    <com.daimajia.numberprogressbar.NumberProgressBar
        android:id="@+id/numberbar1"
        style="@style/NumberProgressBar_Default"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        custom:progress_unreached_bar_height="8dp"
        custom:progress_reached_bar_height="4dp"
        android:padding="20dp"
        custom:progress="0" />
```

**Comment by crysan** [comment]
Yes, really weird. Well, I will understand more. Thank you for your library!

**Comment by daimajia** [comment]
@crysan Can you make sure that you have never called [setUnReadchedbarHeight](https://github.com/daimajia/NumberProgressBar/blob/master/library/src/main/java/com/daimajia/numberprogressbar/NumberProgressBar.java#L386) method in Activity?

**Comment by crysan** [comment]
The library does not have this method, there is only getReachedBarHeight ().

**Comment by daimajia** [comment]
https://github.com/daimajia/NumberProgressBar/blob/master/library/src/main/java/com/daimajia/numberprogressbar/NumberProgressBar.java#L386

**Comment by daimajia** [comment]
Try create a blank project and import this library, and copy the layout from example folder, just change the `progress_reached_bar_height ` attribute. and check if it works.

**Comment by crysan** [comment]
http://lvkr.ru/BCayks.jpg

**Comment by crysan** [comment]
Try create a blank project and import this library, and copy the layout from example folder, just change the progress_reached_bar_height attribute. and check if it works.

**Comment by crysan** [comment]
Did you say - does not work!

**Comment by daimajia** [comment]
I mean create a new project , only add numberprogressbar into you layout xml. and check the attributes work or not.

**Comment by crysan** [comment]
So I did - is not working. It does not change the line thickness. Method setUnReadchedbarHeight just not.

**Comment by crysan** [comment]
Unfortunately, it never happened ((

**Comment by crysan** [comment]
Нашел в чем причина:
Android Studio created description
xmlns:custom="http://schemas.android.com/tools"

should be replaced by
xmlns:custom="http://schemas.android.com/apk/res-auto"

Thanks for your help and patience!

**Comment by Rekam** [comment]
I replaced by  xmlns:custom="http://schemas.android.com/apk/res-auto", still not work !!! @@ ~~

**Comment by tux-world** [comment]
this library work correctly when i install that from gradle on android
studio

**Comment by Rekam** [comment]
I also install library from gradle on android studio by using below code: 
dependencies {
   compile 'com.daimajia.numberprogressbar:library:1.2@aar'
}

Basically, It work very well, but I found something wrong about set Attribute, eg. custom:progress_unreached_bar_height="4dp" 
And I can't import com.daimajia.numberprogressbar.OnProgressBarListener;

Maybe is there another way to access the library correctly???
Sorry about I'm newbie about android development. @@~~

**Comment by Dona278** [comment]
Try with https://github.com/Dona278/NumberProgressBar
All of attributes are renamed to prevent conflicts with other libraries

**Comment by daimajia** [comment]
@Rekam Hey, the latest version 1.3 has been releases. It should be fixed, please try it.

**Comment by Coehill** [comment]
I'm getting this problem too.  I have set `app:progress_unreached_bar_height="16dp"` and `app:progress_reached_bar_height="16dp"` but they are not affecting the bar height.
