### ISSUE TITLE
Can't implement OnProgressBarListener 

### ISSUE THREAD

**Issue by AbhiratTermsirichit** [daimajia/NumberProgressBar#21]
Excuse Me 
I have a issue 
I can't implement OnProgressBarListener after import your library from  gradle,Can tell me how to implement for fix the issue please
sorry my english is bad 
abhirat.term@gmail.com

**Comment by alvarolloret** [comment]
Same problem, `OnProgressBarListener` not imported from Gradle!

**Comment by Dona278** [comment]
Try with https://github.com/Dona278/NumberProgressBar

**Comment by daimajia** [comment]
Fixed in version 1.3. (Because old version wasn't include the latest code.)
