### ISSUE TITLE
I can't use the method "setOnProgressBarListener"

### ISSUE THREAD

**Issue by lihongxiangleo** [daimajia/NumberProgressBar#24]
Excusme!daimajia.
I hava a issue that I cant use the method 'setOnProgressBarListener'.
![image](https://cloud.githubusercontent.com/assets/12996465/9082987/50ce57fe-3b9a-11e5-9878-fe6a0e5467b4.png)
and I can't import the package :
![image](https://cloud.githubusercontent.com/assets/12996465/9083033/9276d28a-3b9a-11e5-9c9c-3ed50a38ac41.png)
can you tell me how to use this method?
my email adress is lihongxiangleo@gmail.com.

**Comment by AndroidLTG** [comment]
how to resolve it ?

**Comment by lihongxiangleo** [comment]
Sorry！I dont knowT T

**Comment by AndroidLTG** [comment]
T_T

**Comment by daimajia** [comment]
@lihongxiangleo @AndroidLTG  Clone the latest code and import this project in yours may solve this problem.
