### ISSUE TITLE
Absolute Figures

### ISSUE THREAD

**Issue by XxGoliathusxX** [daimajia/NumberProgressBar#30]
I want to show stages the user can reach. How can I display that he has done 3 of 5 stages for example? Instead of releative 60% i want to set 3/5.

**Comment by huan51025** [comment]
private void calculateDrawRectF() {
        mCurrentDrawText = String.format("%d", getProgress() * 100 / getMax());
change to
mCurrentDrawText = String.format("%d", getProgress());

**Comment by Dona278** [comment]
@XxGoliathusxX Try with https://github.com/Dona278/NumberProgressBar
I've added custom value as a string. You can combine this and other attributes like suffix to customize progress text.

**Comment by daimajia** [comment]
Thanks for your help @huan51025 .
