### ISSUE TITLE
SetAttributes doesnt work

### ISSUE THREAD

**Issue by JAsenjo** [daimajia/NumberProgressBar#31]
No way to setmax, programmatically or xml.

:(

**Comment by JAsenjo** [comment]
No way to setmax, programmatically or xml...


:(

**Comment by JAsenjo** [comment]
No way to setmax, programmatically or xml.

:(

**Comment by Dona278** [comment]
Try with https://github.com/Dona278/NumberProgressBar
I've fixed some of bugs relative to using attributes

**Comment by daimajia** [comment]
@JAsenjo It has been fixed in Version 1.3, please check it.
