### ISSUE TITLE
 Caused by: java.lang.ClassCastException: com.daimajia.numberprogressbar.NumberProgressBar cannot be cast to android.widget.ProgressBar

### ISSUE THREAD

**Issue by Jacko07** [daimajia/NumberProgressBar#32]
what's wrong?

**Comment by tux-world** [comment]
I think this error isn't for this librry, i have this error long time. please remove widget and create again. may be you should restart AndroidStudio.


i hope to help you

**Comment by Dona278** [comment]
@Jacko07 It's not possible cast NumberProgressBar to ProgressBar because is an extended class of a generic View
```Java
public class NumberProgressBar extends View
```
In your activity you must use directly NumberProgressBar class to have access to their methods, otherwise you use a simple View class

**Comment by daimajia** [comment]
@Dona278 Thanks for your help on this thread. 

@Jacko07 It has no relation with the `android.widget.ProgressBar`.
