### ISSUE TITLE
no OnProgressBarListener

### ISSUE THREAD

**Issue by jy617lee** [daimajia/NumberProgressBar#36]
I add below to build.gradle 
compile 'com.daimajia.numberprogressbar:library:1.2@aar'

however, when to build, 
there's no progress_max and progress_current attribute
and can not reach to OnProgressBarListener. 

when I go to NumberProgressBar.java, 
it is different from what I can see in this repository. 

May I get any help? is it matter of different version?

**Comment by android20285** [comment]
good

**Comment by Dona278** [comment]
Try with https://github.com/Dona278/NumberProgressBar

**Comment by daimajia** [comment]
Fixed, please try version 1.3.
