### ISSUE TITLE
Animation Functionality

### ISSUE THREAD

**Issue by ivanstojkovicapps** [daimajia/NumberProgressBar#43]
Hi,

is there any implemented animation functionality?

best regards Ivan

**Comment by daimajia** [comment]
Animation? What kind of animation?

**Comment by ivanstojkovicapps** [comment]
like when activity starts that progress bar goes from 0 to X %.
Currently i am doing it with: 
`Timer timer = new Timer();
    timer.schedule(new TimerTask() {
      @Override
      public void run() {
        activity.runOnUiThread(new Runnable() {
          @Override
          public void run() {
            if(progressBar.getProgress() < maxPercent) {
              progressBar.incrementProgressBy(1);
            }
          }
        });
      }
    }, 1000, 20);
`
One more thing, why is last release 1.2 from 2014, there are no attributes like 

`custom:progress_unreached_bar_height="4dp"
                    custom:progress_reached_bar_height="8dp"
                    custom:progress_text_size="16dp"
                    custom:progress="0"`

in current version 1,2

**Comment by daimajia** [comment]
Transition animation will be supported in next version. Currently not support.

**Comment by daimajia** [comment]
Thanks for your advice.

**Comment by ivanstojkovicapps** [comment]
Thanks! Nice Work.

Is there any reason that last release is from 2014. What is the latest version that should be used in gradle?

**Comment by daimajia** [comment]
Ha, there happened a lot of things since 2014. Too busy to take care my open source projects. But now, I think I'm back. 🎉

**Comment by daimajia** [comment]
There is a PR https://github.com/daimajia/NumberProgressBar/pull/35 which archived what you want, but I can't merge it, because It may get error or bad effect in some cases. It's not perfect enough.

**Comment by daimajia** [comment]
BTW. You can always get the version info here : http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.daimajia.numberprogressbar%22

**Comment by ivanstojkovicapps** [comment]
is there a way to tell gradle to use last commit and not release 1.2?

**Comment by daimajia** [comment]
@ivanstojkovicapps Change 1.2 -> 1.1

**Comment by ivanstojkovicapps** [comment]
Thanks, i tried this 
compile 'com.daimajia.numberprogressbar:library:1.1'

Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute application@icon value=(@mipmap/ic_launcher) from AndroidManifest.xml:9:9-43
  	is also present at [com.daimajia.numberprogressbar:library:1.1] AndroidManifest.xml:4:45-81 value=(@drawable/ic_launcher).
  	Suggestion: add 'tools:replace="android:icon"' to <application> element at AndroidManifest.xml:6:5-25:19 to override.

**Comment by daimajia** [comment]
Oh, it's an old bug, better not use 1.1 anymore.

**Comment by ivanstojkovicapps** [comment]
so you suggest: compile 'com.daimajia.numberprogressbar:library:1.2'
but there is a problem that the attributes are not working, when i use 1.2

**Comment by daimajia** [comment]
@ivanstojkovicapps which attribute? `unreachedHeight` ?

**Comment by ivanstojkovicapps** [comment]
```
custom:progress_unreached_bar_height="4dp"
                    custom:progress_reached_bar_height="8dp"
                    custom:progress_text_size="16dp"
                    custom:progress="0"
```

**Comment by ivanstojkovicapps** [comment]
none of those is working and there are no methods to set it programatically

**Comment by daimajia** [comment]
![image](https://cloud.githubusercontent.com/assets/2503423/23216687/ccfd3270-f951-11e6-9731-ccf813bfda4e.png)

Make sure that you have added the highlight line in XML file. I just tested, it works well.

**Comment by daimajia** [comment]
```xml
xmlns:custom="http://schemas.android.com/apk/res-auto"
```

**Comment by ivanstojkovicapps** [comment]
thanks, that was set wrong! Great!

**Comment by daimajia** [comment]
Version 1.3 has been released, please try the latest version of this lib. Lots of issues has been fixed.

**Comment by ivanstojkovicapps** [comment]
thanks already got it!

**Comment by daimajia** [comment]
This thread will be closed, the feature will be archived in next version, thanks for your feedback. Have a nice day.

**Comment by Coehill** [comment]
@daimajia  Hey did animation functionality get completed?  If so, how does one use it?
