### ISSUE TITLE
 Attribute "progress_text_visibility" already defined with incompatible format.

### ISSUE THREAD

**Issue by stormlei** [daimajia/NumberProgressBar#45]
@daimajia

**Comment by daimajia** [comment]
Could you show me your gradle dependency section content? I guess there is another lib which also defined `progress_text_visibility` attribute.

**Comment by stormlei** [comment]
you are right.

compile 'com.cjj.materialrefeshlayout:library:1.3.0'

**Comment by daimajia** [comment]
@stormlei I see, you need to do some modification on one of these. For example git clone and change the default style name.

**Comment by stormlei** [comment]
Do not you intend to change your library?

**Comment by daimajia** [comment]
Sorry, it will affect a lot projects which is dependent on this lib. It's not worth doing that. Sorry again.

**Comment by stormlei** [comment]
understand, understand, thank you!
